From php:8.1-fpm

# Install les dépendances
RUN apt-get update && apt-get install -y \
    git unzip libzip-dev zip curl gnupg2 ca-certificates \
    nodejs npm build-essential \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip